---
# This is a sample database file for the DataMapper ORM
development: &defaults
  adapter: postgresql
  database: quebee
  host: 127.0.0.1
#  port: 5434
  port: 5432
  username: quebee
  password: quebee
# NOT SUPPORTED BY dm-rails 1.0.4
  template: template0
  
  # These are the settings for repository :default
  # adapter:  sqlite3
  # database: sample_development.db
 
  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  sqlite3
  #     database: sample_1_development.db
  #   repo2:
  #     ...


test:
  <<:       *defaults
  database: quebee_test
 
  # repositories:
  #   repo1:
  #     database: sample_1_test.db
 
production:
  <<:       *defaults
  database: quebee_production
 
  # repositories:
  #   repo1:
  #     database: sample_production.db
 
#rake:
#  <<: *defaults
