# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

# HACK FOR createdb and -T template 0 dm-rails is broken.
ENV['PATH'] = "#{File.expand_path('../script', __FILE__)}:#{ENV['PATH']}"

require File.expand_path('../config/application', __FILE__)
require 'rake'

Quebee::Application.load_tasks
